/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/my/Album.vue')['default']
    AreaPicker: typeof import('./src/components/my/edit/AreaPicker.vue')['default']
    Basic: typeof import('./src/components/my/edit/Basic.vue')['default']
    Calendar: typeof import('./src/components/my/edit/Calendar.vue')['default']
    Container: typeof import('./src/components/home/Container.vue')['default']
    CreateAlbum: typeof import('./src/components/my/CreateAlbum.vue')['default']
    Device: typeof import('./src/components/my/edit/Device.vue')['default']
    EditAlbum: typeof import('./src/components/my/EditAlbum.vue')['default']
    Header: typeof import('./src/components/home/Header.vue')['default']
    ImgCrop: typeof import('./src/components/img-crop/img-crop.vue')['default']
    Money: typeof import('./src/components/my/edit/Money.vue')['default']
    Order: typeof import('./src/components/my/edit/Order.vue')['default']
    Photo: typeof import('./src/components/my/edit/Photo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./src/components/order/Schedule.vue')['default']
    Tab: typeof import('./src/components/home/Tab.vue')['default']
    Webview: typeof import('./src/components/webview/index.vue')['default']
  }
}
